### PR TITLE
bsd-user: Don't truncate the return value from freebsd_syscall

### LINKED ISSUE #40: blitz branch seems broken, at least for aarch64 chroots.
In my test setup, I have binmisc entries setup *without* pre-open. I have a small arm64 chroot containing pkgbase's FreeBSD-runtime and supporting packages.
I tested with both sysutils/qemu-user-static and sysutils/qemu-user-static-devel by copying qemu-aarch64-static into the chroot's /usr/local/bin and run ```chroot <dir> sh``` sucessfully.
I built an emulator from blitz which does not contain my execve changes:
```
$ mkdir build
$ cd build && ../configure --prefix=/usr/local --cc=cc --localstatedir=/var --extra-ldflags=-L/usr/local/lib --extra-cflags=-I/usr/local/include --enable-debug --enable-debug-info --static --python=/usr/local/bin/python3.9 --disable-docs --disable-tools --disable-system --disable-capstone --extra-cflags='-I/usr/local/include -DPREFIX=\""/usr/local\""' --target-list=i386-bsd-user,arm-bsd-user,ppc-bsd-user,x86_64-bsd-user,riscv64-bsd-user,ppc64-bsd-user,aarch64-bsd-user
$ gmake -j16 
...
```
If I copy this emulator into my chroot, I get this:
```
# chroot $m sh
ld-elf.so.1: Shared object "libedit.so.8" not found, required by "sh"
```
poking around with ktrace shows that the emulator runs and appears to be executing the chroot's /libexec/ld-elf.so.1, opens /var/run/ld-elf.so.hints and then prints the above error message. Interestingly, it doesn't even try to open libedit.so.8.

_Originally posted by @dfr in https://github.com/qemu-bsd-user/qemu-bsd-user/issues/39#issuecomment-1344155962_

### PR DESCRIPTION
**Pull request by dfr**
This was being assigned into an int variable which causes problems for 64bit targets. Fixes #40.

Signed-off-by: Doug Rabson <dfr@rabson.org>

### CODE REVIEW

**Comment by bsdimp** [comment]
I just reopened it. Maybe the robot will respect that... If not, don't worry that it's closed....  I'll get it in.
I need to figure out how to turn off the github actions... they were likely inherited in the fork somehow....

File: bsd-user/freebsd/os-syscall.c [hunk 1]
```diff
@@ -1898,7 +1898,7 @@ abi_long do_freebsd_syscall(void *cpu_env, int num, abi_long arg1,
                             abi_long arg8)
 {
     CPUState *cpu = env_cpu(cpu_env);
-    int ret;
+    abi_long ret;
```
Comment (bsdimp) [inline bsd-user/freebsd/os-syscall.c:1901]: Doh! This looks good to me...

**Comment by bsdimp** [comment]
I had some unpushed changes in my tree, but this is ready to roll..

**Comment by bsdimp** [comment]
I'll also queue it for upstreaming... I'd taken a break from that as I was working on kboot...
